Repository hmcts/finrem-evidence-management-client-api, pull requests merged in 2019-02, with the labels that each got.

#4 HS:FR-653: Adding details to health status response
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/uk/gov/hmcts/reform/emclient/health/WebServiceHealthCheck.java
  src/test/java/uk/gov/hmcts/reform/emclient/health/WebServiceHealthCheckTest.java
Labels: ns:finrem-emca-pr-4

#7 HS: FR-655 : Adding swagger support.
  Dockerfile
  build.gradle
  src/main/java/uk/gov/hmcts/reform/emclient/EvidenceManagementClientApplication.java
  src/main/java/uk/gov/hmcts/reform/emclient/configuration/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientController.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/reform/emclient/EvidenceManagementClientApplicationTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/configuration/SwaggerConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientControllerTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/functional/EvidenceManagementDeleteFunctionalTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/functional/HealthCheckFunctionalTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/validation/validator/EvidenceFileValidatorTest.java
Labels: ns:finrem-emca-pr-7

#8 FR_716_smoke_tests
  build.gradle
  src/smokeTest/java/uk/gov/hmcts/reform/emclient/smoketests/EmClientSmokeTests.java
  src/smokeTest/java/uk/gov/hmcts/reform/emclient/smoketests/SmokeTestConfiguration.java
  src/smokeTest/resources/application.properties
Labels: ns:finrem-emca-pr-8

#9 attempt to run functional test on jenkins
  build.gradle
  docker-compose.yml
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EMClientFileUploadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDeleteIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/IDAMUtils.java
  src/integrationTest/resources/application-aat.properties
  src/integrationTest/resources/application-local.properties
  src/integrationTest/resources/application-preview.properties
  src/integrationTest/resources/application.properties
Labels: ns:finrem-emca-pr-9

#10 disable swagger on prod and don't send client stack trace
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  src/main/java/uk/gov/hmcts/reform/emclient/configuration/SwaggerConfiguration.java
  src/main/resources/application.properties
Labels: ns:finrem-emca-pr-10

#11 FR_716_smoke_test_fix
  src/smokeTest/java/uk/gov/hmcts/reform/emclient/smoketests/EmClientSmokeTests.java
  src/smokeTest/resources/application.properties
Labels: ns:finrem-emca-pr-11
