Repository hmcts/finrem-evidence-management-client-api, pull requests merged in 2020-10, with the labels that each got.

#54 dependency check fix
  build.gradle
  src/main/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-54

#55 upgrade to terraform 13
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-55

#56 upgrade versions
  build.gradle
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-56

#57 suppress dependency check error.
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-57
