Repository hmcts/finrem-evidence-management-client-api, pull requests merged in 2020-05, with the labels that each got.

#36 Swap to AAT AKS
  Jenkinsfile_CNP
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, rel:finrem-emca-pr-36

#39 Changing package name
  src/main/java/uk/gov/hmcts/reform/emclient/configuration/EvidenceManagementClientConfiguration.java
Labels: ns:financial-remedy, rel:finrem-emca-pr-39

#40 Supporting both HAL types
  src/main/java/uk/gov/hmcts/reform/emclient/configuration/EvidenceManagementClientConfiguration.java
Labels: ns:financial-remedy, rel:finrem-emca-pr-40

#42 Swap to AKS
  Jenkinsfile_CNP
Labels: ns:financial-remedy, rel:finrem-emca-pr-42

#44 Delete ASE config
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:financial-remedy, rel:finrem-emca-pr-44

#37 Introduced checkstyle and resolved issues
  build.gradle
  checkstyle.xml
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EmClientFileUploadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDeleteIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDownloadIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementTestUtils.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/IDAMUtilsException.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/IdamUtils.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/ServiceContextConfiguration.java
  src/main/java/uk/gov/hmcts/reform/emclient/EvidenceManagementClientApplication.java
  src/main/java/uk/gov/hmcts/reform/emclient/configuration/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalErrorAttributes.java
  src/main/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/emclient/exception/InvalidUriException.java
  src/main/java/uk/gov/hmcts/reform/emclient/health/DefaultHttpEntityFactory.java
  src/main/java/uk/gov/hmcts/reform/emclient/health/EvidenceManagementStoreApi.java
  src/main/java/uk/gov/hmcts/reform/emclient/health/WebServiceHealthCheck.java
  src/main/java/uk/gov/hmcts/reform/emclient/idam/services/UserService.java
  src/main/java/uk/gov/hmcts/reform/emclient/response/FileUploadResponse.java
  src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/emclient/validation/constraint/EvidenceFile.java
  src/main/java/uk/gov/hmcts/reform/emclient/validation/validator/EvidenceFileValidator.java
  src/test/java/uk/gov/hmcts/reform/emclient/controller/EvidenceManagementClientControllerTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalErrorAttributesTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/errorhandler/GlobalExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/functional/BaseFunctionalTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/functional/EvidenceManagementDeleteFunctionalTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/functional/HealthCheckFunctionalTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/idam/UserServiceTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementDownloadServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/service/EvidenceManagementUploadServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/emclient/validation/validator/EvidenceFileValidatorTest.java
Labels: ns:financial-remedy, rel:finrem-emca-pr-37

#45 Removing InstallCharts()
  Jenkinsfile_CNP
  build.gradle
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: ns:financial-remedy, rel:finrem-emca-pr-45
