Repository hmcts/finrem-evidence-management-client-api, pull requests merged in 2020-04, with the labels that each got.

#32 Updating logging dependencies
  build.gradle
Labels: ns:financial-remedy, rel:finrem-emca-pr-32

#34 Fix Swagger for FR Evidence Management Service
  README.md
  build.gradle
Labels: ns:financial-remedy, rel:finrem-emca-pr-34

#35 AKS migration prereqs
  Dockerfile
  Jenkinsfile_CNP
  charts/finrem-emca/Chart.yaml
  charts/finrem-emca/requirements.yaml
  charts/finrem-emca/values.aat.template.yaml
  charts/finrem-emca/values.preview.template.yaml
  charts/finrem-emca/values.yaml
  infrastructure/main.tf
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EMClientFileUploadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/IDAMUtils.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/ServiceContextConfiguration.java
  src/integrationTest/resources/application-aat.properties
  src/integrationTest/resources/application-local.properties
  src/integrationTest/resources/application-preview.properties
  src/integrationTest/resources/application-saat.properties
  src/integrationTest/resources/application.properties
  src/main/java/uk/gov/hmcts/reform/emclient/EvidenceManagementClientApplication.java
  src/main/resources/application.properties
  src/main/resources/bootstrap.yaml
  src/smokeTest/resources/bootstrap.yaml
  src/test/resources/application.properties
Labels: ns:financial-remedy, rel:finrem-emca-pr-35
