Repository hmcts/finrem-evidence-management-client-api, pull requests merged in 2021-09, with the labels that each got.

#73 Dfr 568 fix glassfish vulne
  build.gradle
  charts/finrem-emca/Chart.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-73

#74 Integrate Fortify
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-74

#75 Integrate fortify
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-75

#76 DFR-472: Fix fortify issues
  src/main/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-76
