Repository hmcts/finrem-evidence-management-client-api, pull requests merged in 2022-05, with the labels that each got.

#98 DFR-1052 added multi arch docker image
  Dockerfile
  acb.tpl.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-98

#97 Add Autoscaling Create values.yaml
  charts/finrem-emca/Chart.yaml
  charts/finrem-emca/values.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-97

#99 Bumping tomcat
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-99

#100 Bumping Springframework
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-100
