Repository hmcts/finrem-evidence-management-client-api, pull requests merged in 2022-04, with the labels that each got.

#91 bump springframework
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-91

#94 updating CVE ref
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-94

#96 DFR-1003: Fix failing integration test
  build.gradle
  dependency-check-suppressions.xml
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDeleteIntegrationTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-96
