Repository hmcts/finrem-evidence-management-client-api, pull requests merged in 2022-08, with the labels that each got.

#108 DFR-1086 Update Readme
  README.md
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-108

#109 Add backstage configuration file
  catalog-info.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-109

#110 DFR-1300: fix ft
  Jenkinsfile_nightly
  charts/finrem-emca/Chart.yaml
  charts/finrem-emca/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EmClientFileUploadTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileAuditIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDeleteIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDownloadIntegrationTest.java
  src/integrationTest/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-110

#111 DFR-1300: fix security scan
  audit.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-111
