Repository hmcts/finrem-evidence-management-client-api, pull requests merged in 2023-01, with the labels that each got.

#122 Suppressing bad CVE
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-122

#123 Suppressing snakeyaml dependency
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-123

#124 Bumping Tomcat
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-124

#125 Apache Commons bumps
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-125

#126 DFR-1758: update-chart-version
  charts/finrem-emca/Chart.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/finrem/emclient/EvidenceManagementFileDeleteIntegrationTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-126

#127 DFR-1783: Upgrade charts
  charts/finrem-emca/Chart.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-emca-pr-127
